// Recurring invoices — pure helpers (no I/O), ported from the desktop
// server's generateFromTemplate() so the hosted app's "Generate now" and
// on-open auto-fire produce exactly the same invoice the desktop app did.
import { computeInvoiceTotals, clientYearToDate } from '../utils.js';

/** Today as YYYY-MM-DD in the device's own time zone (IST for our users). */
export const localToday = (d = new Date()) =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

/** Moves a YYYY-MM-DD date on by one recurrence. */
export function advanceDate(dateStr, frequency, interval) {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(dateStr || ''));
  if (!m) return dateStr;
  // Work in local calendar terms so month ends / DST never shift a day.
  const d = new Date(Number(m[1]), Number(m[2]) - 1, Number(m[3]));
  const n = Math.max(1, parseInt(interval, 10) || 1);
  const day = d.getDate();
  const addMonths = (k) => {
    d.setDate(1);
    d.setMonth(d.getMonth() + k);
    const last = new Date(d.getFullYear(), d.getMonth() + 1, 0).getDate();
    d.setDate(Math.min(day, last)); // 31 Jan + 1 month = 28/29 Feb, not 3 Mar
  };
  if (frequency === 'weekly') d.setDate(d.getDate() + 7 * n);
  else if (frequency === 'quarterly') addMonths(3 * n);
  else if (frequency === 'yearly') addMonths(12 * n);
  else addMonths(n);
  return localToday(d);
}

export const templateIsActive = (tpl) => !!tpl && tpl.active !== false;

export const templateHasEnded = (tpl, today) =>
  (tpl.endMode === 'onDate' && !!tpl.endDate && today > tpl.endDate)
  || (tpl.endMode === 'afterN' && !!tpl.maxOccurrences && (tpl.occurrencesCreated || 0) >= tpl.maxOccurrences);

export const isTemplateDue = (tpl, today) =>
  templateIsActive(tpl) && !!tpl.nextDate && tpl.nextDate <= today && !templateHasEnded(tpl, today);

export const prefixForInvoiceType = (type) => ({
  proforma: 'EST',
  quotation: 'QUO',
  'credit-note': 'CN',
  'bill-of-supply': 'BOS',
  composition: 'COMP',
  'delivery-challan': 'DC',
}[type] || 'INV');

/** Picks the business profile a template bills for. */
export function profileForTemplate(tpl, profiles = [], activeProfile = {}) {
  return profiles.find(p => p?.gstin && tpl.ownerGstin && p.gstin === tpl.ownerGstin)
    || profiles.find(p => p?.id && tpl.profileId && p.id === tpl.profileId)
    || profiles.find(p => p?.businessName && p.businessName === (tpl.profileBusinessName || tpl.ownerName))
    || activeProfile || {};
}

/**
 * Builds the bill object for one occurrence of a template.
 * Returns { bill, nextTemplate } — the caller saves both.
 */
export function buildBillFromTemplate({ tpl, profile, invoiceNumber, today, bills = [], now = new Date() }) {
  const client = {
    name: tpl.clientName, state: tpl.clientState, gstin: tpl.clientGstin,
    address: tpl.clientAddress, country: tpl.clientCountry, city: tpl.clientCity,
    pin: tpl.clientPin, email: tpl.clientEmail, phone: tpl.clientPhone,
    isSEZ: !!tpl.isSEZ,
  };
  const items = (tpl.items || []).map(i => ({ ...i, name: i.name || i.description || '' }));
  const ytd = clientYearToDate(bills, tpl.clientName, today);
  const invoiceOptions = { ...(tpl.invoiceOptions || {}), tcsCumulativeThisYear: ytd, tdsCumulativeThisYear: ytd };
  const totals = computeInvoiceTotals({
    items,
    profile,
    client,
    details: { placeOfSupply: tpl.placeOfSupply },
    showGST: invoiceOptions.showGST !== false,
    taxInclusive: !!tpl.taxInclusive,
    invoiceOptions,
  });
  const invoiceType = tpl.invoiceType || 'tax-invoice';
  const bill = {
    id: invoiceNumber,
    clientName: tpl.clientName,
    invoiceNumber,
    invoiceDate: today,
    invoiceType,
    currency: tpl.invoiceOptions?.currency || 'INR',
    totalAmount: totals.total,
    totalTaxAmount: totals.totalTaxAmount,
    status: 'unpaid',
    paidAmount: 0,
    payments: [],
    generatedFrom: tpl.id,
    autoGenerated: true,
    autoGeneratedAt: now.toISOString(),
    data: {
      profile,
      client,
      details: { invoiceNumber, invoiceDate: today, dueDate: '', placeOfSupply: tpl.placeOfSupply || '' },
      items,
      totals,
      invoiceType,
      customTerms: tpl.customTerms || '',
      customNotes: tpl.customNotes || tpl.notes || '',
      extraSections: tpl.extraSections || [],
      invoiceOptions: tpl.invoiceOptions || {},
      taxInclusive: !!tpl.taxInclusive,
    },
  };
  const nextTemplate = {
    ...tpl,
    nextDate: advanceDate(tpl.nextDate || today, tpl.frequency, tpl.interval),
    lastGenerated: today,
    lastInvoiceNumber: invoiceNumber,
    occurrencesCreated: (tpl.occurrencesCreated || 0) + 1,
  };
  return { bill, nextTemplate };
}
