-- ============================================================
-- 002_plans_admin_emails.sql  —  Phase 2: plans, limits, coupons,
-- referrals, admin panel, transactional e-mail.
--
-- Run AFTER 001_security_fixes.sql, in the Supabase SQL editor.
-- Idempotent: safe to run more than once (IF NOT EXISTS / OR REPLACE /
-- DROP ... IF EXISTS everywhere; the plan_limits rows are upserted).
--
-- What it does
--   1. subscriptions: `tier` + `lifetime` columns, new status 'free'
--      (after the 30-day trial unpaid users drop to Free, not locked out)
--   2. plan_limits (generated from shared/plans.js) + gbp_effective_tier()
--   3. Free-plan limits enforced IN THE DATABASE:
--        bills             BEFORE INSERT → 50 invoices / IST calendar month
--        business_profiles BEFORE INSERT → businesses per plan
--      (edits / upserts of an existing row are never blocked)
--   4. my_plan() for the in-app usage meter, founder_slots_left()
--   5. coupons + coupon_redemptions, referral_codes + referrals
--   6. admins + admin_actions (read/written only by the service role)
--   7. email_log (de-duplicates transactional e-mails)
--   8. payment_orders: coupon / GST breakdown / sequential receipt number
--
-- AFTER RUNNING: add yourself as admin (replace the e-mail):
--   INSERT INTO public.admins (email, note) VALUES (lower('you@example.com'), 'owner')
--   ON CONFLICT (email) DO NOTHING;
-- ============================================================
BEGIN;

-- ------------------------------------------------------------
-- 1. subscriptions
-- ------------------------------------------------------------
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS tier     TEXT;
ALTER TABLE public.subscriptions ADD COLUMN IF NOT EXISTS lifetime BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE public.subscriptions DROP CONSTRAINT IF EXISTS subscriptions_status_check;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_status_check
  CHECK (status IN ('trial', 'active', 'expired', 'cancelled', 'free'));
ALTER TABLE public.subscriptions DROP CONSTRAINT IF EXISTS subscriptions_tier_check;
ALTER TABLE public.subscriptions ADD CONSTRAINT subscriptions_tier_check
  CHECK (tier IS NULL OR tier IN ('free', 'starter', 'pro', 'business'));

-- Everybody who paid before Phase 2 bought the ₹99 / ₹999 plan = Starter.
UPDATE public.subscriptions SET tier = 'starter'
 WHERE tier IS NULL AND (status = 'active' OR plan IN ('monthly', 'annual')) AND last_payment_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS subscriptions_status_idx ON public.subscriptions(status);
CREATE INDEX IF NOT EXISTS subscriptions_period_end_idx ON public.subscriptions(current_period_end);
CREATE INDEX IF NOT EXISTS subscriptions_trial_end_idx ON public.subscriptions(trial_end);

-- ------------------------------------------------------------
-- 2. plan_limits — one row per tier (data from shared/plans.js)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.plan_limits (
  tier               TEXT PRIMARY KEY,
  rank               INTEGER NOT NULL,
  invoices_per_month INTEGER,          -- NULL = unlimited
  businesses         INTEGER,          -- NULL = unlimited
  staff_users        INTEGER,
  features           JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.plan_limits ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read plan limits" ON public.plan_limits;
CREATE POLICY "Anyone can read plan limits" ON public.plan_limits FOR SELECT TO anon, authenticated USING (true);
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.plan_limits FROM anon, authenticated;
GRANT SELECT ON public.plan_limits TO anon, authenticated;
GRANT ALL ON public.plan_limits TO service_role;

-- >>> GENERATED by scripts/gen-plan-sql.mjs from shared/plans.js — do not edit by hand
INSERT INTO public.plan_limits (tier, rank, invoices_per_month, businesses, staff_users, features) VALUES
  ('free', 0, 50, 1, 0, '{"removeBranding":false,"multiBusiness":false,"staffUsers":false,"whatsappAutomation":false,"eInvoice":false,"prioritySupport":false}'::jsonb),
  ('starter', 1, NULL, 1, 0, '{"removeBranding":true,"multiBusiness":false,"staffUsers":false,"whatsappAutomation":false,"eInvoice":false,"prioritySupport":false}'::jsonb),
  ('pro', 2, NULL, 3, 2, '{"removeBranding":true,"multiBusiness":true,"staffUsers":true,"whatsappAutomation":true,"eInvoice":false,"prioritySupport":false}'::jsonb),
  ('business', 3, NULL, 10, 10, '{"removeBranding":true,"multiBusiness":true,"staffUsers":true,"whatsappAutomation":true,"eInvoice":true,"prioritySupport":true}'::jsonb)
ON CONFLICT (tier) DO UPDATE SET rank = EXCLUDED.rank, invoices_per_month = EXCLUDED.invoices_per_month,
  businesses = EXCLUDED.businesses, staff_users = EXCLUDED.staff_users, features = EXCLUDED.features, updated_at = NOW();

CREATE OR REPLACE FUNCTION public.gbp_plan_const(p_key TEXT) RETURNS TEXT
LANGUAGE sql IMMUTABLE SET search_path = public AS $fn$
  SELECT CASE p_key
    WHEN 'trial_tier' THEN 'pro'
    WHEN 'founder_cap' THEN '300'
    WHEN 'uncounted_invoice_types' THEN 'quotation,estimate,proforma,delivery-challan'
  END
$fn$;
-- <<< END GENERATED

-- Effective tier right now (mirrors effectivePlan() in shared/plans.js):
-- best of  active paid period · lifetime (Starter) · running trial (Pro)
-- otherwise 'free'. Internal: not callable by app users directly.
CREATE OR REPLACE FUNCTION public.gbp_effective_tier(p_user UUID)
RETURNS TEXT
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  s         public.subscriptions%ROWTYPE;
  best      TEXT := 'free';
  best_rank INTEGER := 0;
  cand      TEXT;
  r         INTEGER;
  created   TIMESTAMPTZ;
BEGIN
  SELECT * INTO s FROM public.subscriptions WHERE user_id = p_user;
  IF NOT FOUND THEN
    -- No row yet (ensure_my_subscription() creates it on first load):
    -- treat a new account as being in its trial.
    SELECT u.created_at INTO created FROM auth.users u WHERE u.id = p_user;
    IF created IS NOT NULL AND created > NOW() - INTERVAL '30 days' THEN
      RETURN public.gbp_plan_const('trial_tier');
    END IF;
    RETURN 'free';
  END IF;

  FOREACH cand IN ARRAY ARRAY[
    CASE WHEN s.status = 'active' AND s.current_period_end > NOW() THEN COALESCE(s.tier, 'starter') END,
    CASE WHEN s.lifetime THEN 'starter' END,
    CASE WHEN s.status <> 'cancelled' AND s.trial_end > NOW() THEN public.gbp_plan_const('trial_tier') END
  ] LOOP
    IF cand IS NOT NULL THEN
      SELECT pl.rank INTO r FROM public.plan_limits pl WHERE pl.tier = cand;
      IF r IS NOT NULL AND r > best_rank THEN best := cand; best_rank := r; END IF;
    END IF;
  END LOOP;
  RETURN best;
END;
$$;
REVOKE ALL ON FUNCTION public.gbp_effective_tier(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.gbp_effective_tier(UUID) TO service_role;

-- ------------------------------------------------------------
-- 3. Limits enforced in the database
-- ------------------------------------------------------------
-- Invoices created per IST calendar month. A counter (not COUNT(*)) so
-- deleting and re-creating bills cannot reset the monthly allowance.
CREATE TABLE IF NOT EXISTS public.usage_counters (
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  period     TEXT NOT NULL,                      -- 'YYYY-MM' (Asia/Kolkata)
  invoices   INTEGER NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, period)
);
ALTER TABLE public.usage_counters ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own usage" ON public.usage_counters;
CREATE POLICY "Users can view own usage" ON public.usage_counters FOR SELECT TO authenticated USING (auth.uid() = user_id);
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.usage_counters FROM anon, authenticated;
GRANT SELECT ON public.usage_counters TO authenticated;
GRANT ALL ON public.usage_counters TO service_role;

CREATE OR REPLACE FUNCTION public.gbp_bills_limit()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_period TEXT := to_char(NOW() AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM');
  v_tier   TEXT;
  v_limit  INTEGER;
  v_used   INTEGER;
BEGIN
  -- Upsert of an existing bill (= an edit) also fires BEFORE INSERT: allow.
  IF EXISTS (SELECT 1 FROM public.bills b WHERE b.id = NEW.id AND b.user_id = NEW.user_id) THEN
    RETURN NEW;
  END IF;
  -- Quotations / estimates / proforma / delivery challans are free.
  IF COALESCE(NEW.invoice_type, 'tax-invoice') = ANY (string_to_array(public.gbp_plan_const('uncounted_invoice_types'), ',')) THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.usage_counters (user_id, period) VALUES (NEW.user_id, v_period)
  ON CONFLICT (user_id, period) DO NOTHING;
  SELECT invoices INTO v_used FROM public.usage_counters
   WHERE user_id = NEW.user_id AND period = v_period FOR UPDATE;

  v_tier := public.gbp_effective_tier(NEW.user_id);
  SELECT invoices_per_month INTO v_limit FROM public.plan_limits WHERE tier = v_tier;
  IF v_limit IS NOT NULL AND v_used >= v_limit THEN
    RAISE EXCEPTION 'PLAN_LIMIT_INVOICES: the % plan allows % invoices per month', v_tier, v_limit
      USING ERRCODE = 'P0001', HINT = 'Upgrade your plan for unlimited invoices.';
  END IF;

  UPDATE public.usage_counters SET invoices = invoices + 1, updated_at = NOW()
   WHERE user_id = NEW.user_id AND period = v_period;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.gbp_bills_limit() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS gbp_bills_limit ON public.bills;
CREATE TRIGGER gbp_bills_limit BEFORE INSERT ON public.bills
  FOR EACH ROW EXECUTE FUNCTION public.gbp_bills_limit();

CREATE OR REPLACE FUNCTION public.gbp_business_limit()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_tier  TEXT;
  v_limit INTEGER;
  v_count INTEGER;
BEGIN
  IF EXISTS (SELECT 1 FROM public.business_profiles p WHERE p.id = NEW.id AND p.user_id = NEW.user_id) THEN
    RETURN NEW;
  END IF;
  v_tier := public.gbp_effective_tier(NEW.user_id);
  SELECT businesses INTO v_limit FROM public.plan_limits WHERE tier = v_tier;
  IF v_limit IS NULL THEN RETURN NEW; END IF;
  -- Serialise concurrent inserts for the same user.
  PERFORM pg_advisory_xact_lock(hashtext('gbp_business_limit:' || NEW.user_id::text));
  SELECT COUNT(*) INTO v_count FROM public.business_profiles WHERE user_id = NEW.user_id;
  IF v_count >= v_limit THEN
    RAISE EXCEPTION 'PLAN_LIMIT_BUSINESSES: the % plan allows % business profile(s)', v_tier, v_limit
      USING ERRCODE = 'P0001', HINT = 'Upgrade to Pro or Business for more businesses.';
  END IF;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.gbp_business_limit() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS gbp_business_limit ON public.business_profiles;
CREATE TRIGGER gbp_business_limit BEFORE INSERT ON public.business_profiles
  FOR EACH ROW EXECUTE FUNCTION public.gbp_business_limit();

-- ------------------------------------------------------------
-- 4. Read helpers for the app
-- ------------------------------------------------------------
-- Usage meter: { tier, invoices_used, invoice_limit, businesses, business_limit, period }
CREATE OR REPLACE FUNCTION public.my_plan()
RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  uid      UUID := auth.uid();
  v_period TEXT := to_char(NOW() AT TIME ZONE 'Asia/Kolkata', 'YYYY-MM');
  v_tier   TEXT;
  pl       public.plan_limits%ROWTYPE;
BEGIN
  IF uid IS NULL THEN RAISE EXCEPTION 'not authenticated' USING ERRCODE = '42501'; END IF;
  v_tier := public.gbp_effective_tier(uid);
  SELECT * INTO pl FROM public.plan_limits WHERE tier = v_tier;
  RETURN jsonb_build_object(
    'tier', v_tier,
    'period', v_period,
    'invoices_used', COALESCE((SELECT invoices FROM public.usage_counters WHERE user_id = uid AND period = v_period), 0),
    'invoice_limit', pl.invoices_per_month,
    'businesses', (SELECT COUNT(*) FROM public.business_profiles WHERE user_id = uid),
    'business_limit', pl.businesses
  );
END;
$$;
REVOKE ALL ON FUNCTION public.my_plan() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.my_plan() TO authenticated;

-- Founder Lifetime seats left (public: shown on the pricing page).
CREATE OR REPLACE FUNCTION public.founder_slots_left()
RETURNS INTEGER
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT GREATEST(0, public.gbp_plan_const('founder_cap')::INTEGER - COUNT(*)::INTEGER)
    FROM public.payment_orders
   WHERE plan = 'founder_lifetime' AND status IN ('paid', 'processing');
$$;
REVOKE ALL ON FUNCTION public.founder_slots_left() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.founder_slots_left() TO anon, authenticated, service_role;

-- ------------------------------------------------------------
-- 5. Coupons & referrals (server-only tables; the API validates)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.coupons (
  code            TEXT PRIMARY KEY CHECK (code ~ '^[A-Z0-9][A-Z0-9_-]{2,31}$'),
  kind            TEXT NOT NULL CHECK (kind IN ('percent', 'flat')),
  value           INTEGER NOT NULL CHECK (value > 0),   -- percent (1-90) or paise
  max_redemptions INTEGER CHECK (max_redemptions IS NULL OR max_redemptions > 0),
  redeemed_count  INTEGER NOT NULL DEFAULT 0,
  valid_until     TIMESTAMPTZ,
  applies_to      TEXT[],                               -- plan ids / tiers; NULL = all
  active          BOOLEAN NOT NULL DEFAULT true,
  note            TEXT,
  created_by      TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT coupons_percent_range CHECK (kind <> 'percent' OR value <= 90)
);
CREATE TABLE IF NOT EXISTS public.coupon_redemptions (
  id         UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  code       TEXT NOT NULL REFERENCES public.coupons(code) ON DELETE CASCADE,
  user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  order_id   TEXT,
  discount   INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (code, user_id)
);

CREATE TABLE IF NOT EXISTS public.referral_codes (
  user_id    UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  code       TEXT NOT NULL UNIQUE CHECK (code ~ '^GBP[A-HJ-NP-Z2-9]{6}$'),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.referrals (
  referred_user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  referrer_user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  code             TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'rewarded', 'void')),
  order_id         TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  rewarded_at      TIMESTAMPTZ,
  CHECK (referred_user_id <> referrer_user_id)
);
CREATE INDEX IF NOT EXISTS referrals_referrer_idx ON public.referrals(referrer_user_id);

-- ------------------------------------------------------------
-- 6. Admin panel
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admins (
  email      TEXT PRIMARY KEY CHECK (email = lower(email)),
  note       TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS public.admin_actions (
  id             BIGSERIAL PRIMARY KEY,
  admin_email    TEXT NOT NULL,
  action         TEXT NOT NULL,
  target_user_id UUID,
  details        JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS admin_actions_created_idx ON public.admin_actions(created_at DESC);

-- ------------------------------------------------------------
-- 7. Transactional e-mail log (dedupe_key makes every send idempotent)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.email_log (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id     UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  kind        TEXT NOT NULL,
  dedupe_key  TEXT NOT NULL UNIQUE,
  to_email    TEXT,
  status      TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'skipped', 'failed')),
  provider_id TEXT,
  error       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS email_log_user_idx ON public.email_log(user_id, created_at DESC);

-- All of section 5-7 is service-role only: RLS on, no policies for users.
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['coupons', 'coupon_redemptions', 'referral_codes', 'referrals', 'admins', 'admin_actions', 'email_log'] LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON public.%I FROM anon, authenticated', t);
    EXECUTE format('GRANT ALL ON public.%I TO service_role', t);
  END LOOP;
END $$;
GRANT USAGE, SELECT ON SEQUENCE public.admin_actions_id_seq TO service_role;

-- ------------------------------------------------------------
-- 8. payment_orders: coupon, GST breakdown, receipt number
-- ------------------------------------------------------------
ALTER TABLE public.payment_orders ADD COLUMN IF NOT EXISTS base_amount    INTEGER;
ALTER TABLE public.payment_orders ADD COLUMN IF NOT EXISTS discount       INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.payment_orders ADD COLUMN IF NOT EXISTS gst_amount     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.payment_orders ADD COLUMN IF NOT EXISTS coupon_code    TEXT;
ALTER TABLE public.payment_orders ADD COLUMN IF NOT EXISTS receipt_number TEXT;
ALTER TABLE public.payment_orders ADD COLUMN IF NOT EXISTS note           TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS payment_orders_receipt_no_idx ON public.payment_orders(receipt_number) WHERE receipt_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS payment_orders_plan_status_idx ON public.payment_orders(plan, status);

-- Sequential receipt numbers per Indian financial year: GBP/2026-27/00001
CREATE TABLE IF NOT EXISTS public.receipt_counters (
  fy      TEXT PRIMARY KEY,
  last_no INTEGER NOT NULL DEFAULT 0
);
ALTER TABLE public.receipt_counters ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.receipt_counters FROM anon, authenticated;
GRANT ALL ON public.receipt_counters TO service_role;

CREATE OR REPLACE FUNCTION public.next_receipt_number(p_at TIMESTAMPTZ DEFAULT NOW())
RETURNS TEXT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  d  DATE := (p_at AT TIME ZONE 'Asia/Kolkata')::DATE;
  y  INTEGER := CASE WHEN EXTRACT(MONTH FROM d) >= 4 THEN EXTRACT(YEAR FROM d)::INTEGER ELSE EXTRACT(YEAR FROM d)::INTEGER - 1 END;
  v_fy TEXT := y::TEXT || '-' || lpad(((y + 1) % 100)::TEXT, 2, '0');
  n  INTEGER;
BEGIN
  INSERT INTO public.receipt_counters AS rc (fy, last_no) VALUES (v_fy, 1)
  ON CONFLICT ON CONSTRAINT receipt_counters_pkey DO UPDATE SET last_no = rc.last_no + 1
  RETURNING rc.last_no INTO n;
  RETURN 'GBP/' || v_fy || '/' || lpad(n::TEXT, 5, '0');
END;
$$;
REVOKE ALL ON FUNCTION public.next_receipt_number(TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.next_receipt_number(TIMESTAMPTZ) TO service_role;

-- Atomic coupon redemption counter (called by the server on activation).
CREATE OR REPLACE FUNCTION public.redeem_coupon(p_code TEXT)
RETURNS VOID
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  UPDATE public.coupons SET redeemed_count = redeemed_count + 1, updated_at = NOW() WHERE code = p_code;
$$;
REVOKE ALL ON FUNCTION public.redeem_coupon(TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_coupon(TEXT) TO service_role;

COMMIT;
